window.GAME_CONFIG = Object.assign({}, window.BRAINROT_DEFAULTS, {
  template: "../_templates/brainrot/",
  variant: "save",
  saveKey: "save-a-brainrot",
  mpGame: "save-a-brainrot",
  chatRoom: "save-a-brainrot",
  zones: [
    {
      id: 0,
      name: "🏭 Rescue HQ",
      mobLevel: 0,
      reqLevel: 1,
      isPier: true,
      floor: "hsl(280, 45%, 38%)",
      floorAlt: "hsl(300, 50%, 48%)",
      decor: "pier",
      skyTop: "hsl(280, 55%, 28%)",
      skyBot: "hsl(300, 65%, 62%)",
      mobs: [],
      bossColor: "hsl(280, 55%, 55%)",
    },
    {
      id: 1,
      name: "🎪 Neon Midway",
      mobLevel: 1,
      reqLevel: 1,
      floor: "hsl(320, 60%, 45%)",
      floorAlt: "hsl(340, 55%, 55%)",
      decor: "ocean",
      skyTop: "hsl(300, 50%, 25%)",
      skyBot: "hsl(320, 70%, 65%)",
      mobs: ["mob0", "mob1", "mob2"],
      bossType: "bossAlpha",
      bossColor: "hsl(330, 60%, 50%)",
    },
    {
      id: 2,
      name: "🗑️ Junkyard",
      mobLevel: 5,
      reqLevel: 4,
      floor: "hsl(40, 35%, 35%)",
      floorAlt: "hsl(25, 40%, 42%)",
      decor: "coral",
      skyTop: "hsl(30, 45%, 28%)",
      skyBot: "hsl(45, 55%, 58%)",
      mobs: ["mob3", "mob4", "mob5"],
      bossType: "bossBeta",
      bossColor: "hsl(35, 50%, 45%)",
    },
    {
      id: 3,
      name: "☁️ Cloud Kingdom",
      mobLevel: 10,
      reqLevel: 8,
      floor: "hsl(200, 55%, 72%)",
      floorAlt: "hsl(210, 60%, 82%)",
      decor: "ice",
      skyTop: "hsl(220, 70%, 55%)",
      skyBot: "hsl(200, 80%, 88%)",
      mobs: ["mob6", "mob7", "mob8"],
      bossType: "bossGamma",
      bossColor: "hsl(210, 65%, 60%)",
    },
    {
      id: 4,
      name: "🌋 Magma Pit",
      mobLevel: 15,
      reqLevel: 12,
      floor: "hsl(12, 65%, 38%)",
      floorAlt: "hsl(8, 70%, 48%)",
      decor: "lava",
      skyTop: "hsl(5, 75%, 25%)",
      skyBot: "hsl(20, 80%, 55%)",
      mobs: ["mob9", "mob10", "mob11"],
      bossType: "bossDelta",
      bossColor: "hsl(10, 70%, 45%)",
    },
    {
      id: 5,
      name: "🌊 Abyss Dock",
      mobLevel: 20,
      reqLevel: 16,
      floor: "hsl(230, 50%, 28%)",
      floorAlt: "hsl(240, 55%, 38%)",
      decor: "depths",
      skyTop: "hsl(250, 60%, 18%)",
      skyBot: "hsl(220, 65%, 45%)",
      mobs: ["mob12", "mob13", "mob14"],
      bossType: "bossOmega",
      bossColor: "hsl(235, 55%, 42%)",
    },
  ],
  loadingTips: [
      "Rescue brainrots before time runs out!",
      "Walk up to 💾 markers in the field to save!",
      "Travel zones to find more rescues!"
  ],
  features: [
      "💾 Rescue stranded brainrots in wild zones",
      "⏱️ Clear all rescues before they despawn",
      "🏠 Walk home base to merge saved brainrots",
      "♻️ Rebirth for faster rescue rewards",
      "👥 Team up with friends online!"
  ],
  ui: Object.assign({}, window.BRAINROT_DEFAULTS.ui, {
        "shopSubtitle": "Rescue gear — Save A Brainrot!",
        "fightBtn": "💾 Rescue"
    }),
  branding: {
    title: "Save A Brainrot",
    description: "Rescue brainrots before time runs out!",
    playBtn: "Play Now!"
  }
});
